# Usar a imagem oficial do Node.js como base
 FROM node:18

 # Definir o diretório de trabalho dentro do contêiner
 WORKDIR /app

 # Copiar o arquivo package.json e package-lock.json
 COPY package*.json ./

 # Instalar as dependências do projeto
 RUN npm install

 # Copiar o restante do código do projeto para o contêiner
 COPY . .

 # Expor a porta que o servidor irá utilizar (neste exemplo, 5000)
 EXPOSE 5000

 # Comando para iniciar o servidor
 CMD ["npm", "start"]
